version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
      ports:
        - "80:8080"
    depends_on:
      - spring
  spring:
    image: springci/spring-boot-ci-image
    deploy:
      replicas: 3
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ArquiteturaEmNuvem10