version: "3"
services:
  proxy:
      image: httpd
      depends_on:
        - web
  web:
    image: microsoft/dotnet:2.1-aspnetcore-runtime
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux
    environment: 
        SA_PASSWORD: "ArquiteturaEmNuvem10"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"